name: flutter_code_editor
description: A customizable code field supporting syntax highlighting and code folding.
version: 0.3.0
repository: https://github.com/akvelon/flutter-code-editor

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter: 
    sdk: flutter

  autotrie: 
    path: ../autotrie
  characters: ^1.2.1 ## active (dart.dev)
  charcode: ^1.3.1 ## active (infimum.dk)
  collection: ^1.16.0 ## active (dart.dev)
  equatable: ^2.0.5 ## inactive (fluttercommunity.dev)
  flutter_highlight: ^0.7.0 ## inactive (unknown)
  highlight: ^0.7.0 ## inactive (unknown)
  http: ^1.1.0 ## active (dart.dev)
  linked_scroll_controller: ^0.2.0 ## inactive (google.dev)
  meta: ^1.7.0 ## active dart.dev
  mocktail: ^1.0.0 ## active (felangel.dev)
  scrollable_positioned_list: ^0.3.5 ## active (google.dev)
  tuple: ^2.0.1 ## active (google.dev)
  url_launcher: ^6.1.8 ## active (flutter.dev)

dev_dependencies:
  fake_async: ^1.3.1 ## inactive (dart.dev)
  flutter_test: 
    sdk: flutter
  total_lints: ^3.0.0 ## active (ainkin.com)

flutter:
  uses-material-design: true
